### ISSUE TITLE
Issue with using OHHTTPStubs

### ISSUE THREAD

**Issue by arkmon** [netguru/hubguru-ios-public#5]
***  Skipped installing OHHTTPStubs.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.1 (swiftlang-802.0.53 clang-802.0.42) and the local version is 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1).

Had to try with `--no-use-binaries` in order to install that framework. Maybe there are other solutions, like lowering the swift version in the project?

**Comment by sochalewski** [comment]
Hey @arkmon 

You don't need to add `--no-use-binaries`. This message from Carthage is a warning, not an error:

```
***  Skipped installing OHHTTPStubs.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.1 (swiftlang-802.0.53 clang-802.0.42) and the local version is 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)."

    Falling back to building from the source
```

As you can see in the last line Carthage rebuilds it using the proper Swift version, so you don't have to worry about it.

It eventually builds `Carthage⁩/Build⁩/⁨iOS⁩/OHHTTPStubs.framework` for you.

**Comment by arkmon** [comment]
👍🏻
